#!/usr/bin/bash

help(){
echo "This script gives you an easy way to use useful pacman abilities not directly provided by pacman options.
It does not aim to replace pacman.

-h , --help
	Shows help and quit Programm
-I , --info
	Shows more Information about this script. Useful if you want to learn more about Pacman :)
-a , --autoremove
	Remove unessesary packages
-r , --remove {Package name}
	Remove a package (Wildcard support)
	example: $0 --remove python2-*
-i , --install {Package name}
	Install a package (Wildcard support)
	example: $0 --install xfce4-*-plugin

If you do not need wildcard, please use pacman or paru instead
Use the Program at your own risk and please make sure to check the pacman output before making changes to your System.
Script under GPL3 License https://github.com/LeSnake04/pacman-extra-tools/blob/main/LICENSE
Bug reports, contributions, and feature requests welcome at https://github.com/LeSnake04/pacman-extra-tools
"	
}

info(){
	echo "After having to search for many pacman hidden functions myself, i decided to help others by giving others by giving them an easy way to use the functions i found. :)
if you dont trust my script and want to use the functions directly, you are welcome to copy the lines from here:

Autoremove:
TODO: Autoremove command

Install:
sudo pacman -Sy $(pacman -Ssq | grep SEARCH_TERM )

Remove:
sudo pacman -Rsu $(pacman -Qq | grep SEARCH_TERM )
	"
}

ARGS=$(getopt -n $0 \
 -o ahr:i:I \
 --long autoremove,help,remove:,install:,info \
 -- "$@")
echo "$ARGS"
if [ "$ARGS" = " --" ]; then
	help
else 
	for arg in $ARGS; do
		echo $arg
		case $arg in
			-a | --autoremove )
				echo autoremove
			;;
			-I --info )
				echo
			# quit program at end of options
			--) 
				break
			;;
			*)
				help
		esac
	done
fi
